import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useTheme } from '../../context/theme_context';

export default function PrivacyPolicyScreen() {
  const { themeStyles, textSize } = useTheme();

  return (
    <View style={[styles.container, themeStyles.container]}>
      <View style={styles.pageTitleWrapper}>
        <Text style={[styles.pageTitleText, themeStyles.text]}>
          Privacy & Legal{"\n"}Information
        </Text>
      </View>
      <ScrollView style={{ paddingTop: 10 }}>
        <View style={[styles.infoCard, themeStyles.card]}>
          <Text style={[styles.subHeaderText, themeStyles.text, { fontSize: textSize + 4 }]}>
            Privacy Policy
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            1. Overview
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            MediDex ("the App") is committed to protecting your privacy. This Privacy Policy outlines the type of data we collect,
            how it is used, and your rights regarding your information when using the App.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            2. No Collection of Personal Data
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            MediDex does not collect, store, transmit, or share any personally identifiable information (PII). The App does not
            require user registration or login, and no user data is sent to our servers, to Medsafe New Zealand, or to any third
            parties.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            3. Local Data Use
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            Any data generated by your use of MediDex (e.g., viewed medicines, saved preferences, or settings) is stored locally
            on your device only and used solely for the purpose of enhancing your experience within the App. This data is not
            accessible to us or any external party.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            4. Data Retention and Deletion
          </Text>
          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            MediDex does not retain any user data once the App is uninstalled. All locally stored information is removed automatically
            as part of the standard app uninstallation process.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            5. Third-Party Services
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            MediDex does not integrate with advertising networks, analytics services, or third-party platforms that track user behavior
            or collect personal data.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            6. Children's Privacy
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            MediDex is not intended for use by individuals under the age of 16. We do not knowingly collect or store personal data
            from children.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            7. Changes to This Privacy Policy
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            We may update this Privacy Policy from time to time. When we do, we will revise the "Effective Date" at the top of the
            policy. Continued use of the App after changes indicates your acceptance of the updated policy.
          </Text>
        </View>

        <View style={[styles.infoCard, themeStyles.card]}>

          <Text style={[styles.subHeaderText, themeStyles.text, { fontSize: textSize + 4 }]}>
            Legal Information
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize, fontStyle: 'italic' }]}>
            By using the MediDex application ("the App"), you agree to the following terms and conditions, governed by the laws of New
            Zealand:
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            1. Source of Information
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            All information provided in the App is sourced directly from Medsafe New Zealand. The content is unaltered except for formatting to
            improve readability. While we strive to ensure the information is current, there may be delays between Medsafe releases and app
            updates.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            2. Scope of Recall Data
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            Recall notices included in MediDex cover a rolling 180-day period and are limited to medicines only. Information about medical devices
            is not included. We do not guarantee completeness of recall data outside this scope.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            3. Use of Consumer Medicine Information (CMI)
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            Not all medicines listed in MediDex have an official CMI (Consumer Medicine Information) sheet available from Medsafe. In such cases,
            we may provide a CMI sheet from a similar medicine containing the same active ingredient(s) and dosage(s). These substitute CMIs are intended as
            general guidance only and may not reflect specific differences in formulation, brand, or patient advice. Users are strongly encouraged
            to consult a healthcare professional for clarification and personalised information.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            4. Medical Disclaimer
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            The App is intended for informational purposes only and does not replace professional medical advice. You must consult a qualified
            doctor, pharmacist, or healthcare professional before making any medical decisions. Reliance on the information provided in the App
            is at your own risk.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            5. Privacy and Data
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            MediDex does not collect, store, or transmit any personal or health-related information. No data is sent to Medsafe or any other external
            party. Any data stored locally is deleted upon uninstallation.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            6. Intellectual Property
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            All content, layout, and formatting in MediDex are the intellectual property of the creators. You may not copy, reproduce, distribute, or
            link to any part of the App or its content without prior written permission.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            7. Limitation of Liability
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            To the maximum extent permitted under New Zealand law, MediDex and its creators accept no liability for any direct or indirect loss,
            damage, or injury resulting from the use of the App or reliance on its content.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            8. Amendments
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            We reserve the right to update or modify these Terms at any time without notice. Continued use of the App indicates your acceptance of
            any revised Terms.
          </Text>

          <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>
            9. Governing Law
          </Text>

          <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>
            These Terms are governed by the laws of New Zealand. Any disputes arising in connection with the App shall be subject to the exclusive
            jurisdiction of the New Zealand courts.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    paddingTop: 40,
    paddingHorizontal: 15,
    backgroundColor: '#f0f8ff',
    flex: 1,
  },
  pageTitleWrapper: {
    alignItems: 'center',
    marginTop: 40,
    marginBottom: 20
  },
  pageTitleText: {
    fontSize: 40,
    color: '#336699',
    textAlign: 'center'
  },
  headerText: {
    textAlign: 'left',
    marginTop: 10,
    marginBottom: 4,
    fontWeight: "bold"
  },
  subHeaderText: {
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 4,
    fontWeight: "bold",
    textDecorationLine: 'underline'
  },
  bodyText: {
    textAlign: 'left',
    marginBottom: 5,
    fontWeight: 'normal'
  },
  infoCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 14,
    elevation: 3,
    marginBottom: 25,
    marginHorizontal: 4
  }
});