import React from 'react'
import { ScrollView, StyleSheet, Text, View } from 'react-native'
import { useTheme } from '../../context/theme_context'

export default function PrivacyPolicyScreen() {
  const { themeStyles, textSize } = useTheme()

  return (
    <View style={[styles.container, themeStyles.container]}>
      <View style={styles.pageTitleWrapper}>
        <Text style={[styles.pageTitleText, themeStyles.text]}>
          Privacy & Legal Information
        </Text>
      </View>

      <ScrollView style={{ paddingTop: 10 }}>
        <View style={[styles.infoCard, themeStyles.card]}>
          <Text style={[styles.subHeaderText, themeStyles.text, { fontSize: textSize + 4 }]}>
            Privacy Policy
          </Text>

          {[
            {
              title: '1. Overview',
              body: `MediDex ("the App") is committed to protecting your privacy...`
            },
            {
              title: '2. No Collection of Personal Data',
              body: `MediDex does not collect, store, transmit, or share any personally identifiable information (PII)...`
            },
            {
              title: '3. Local Data Use',
              body: `Any data generated by your use of MediDex...`
            },
            {
              title: '4. Data Retention and Deletion',
              body: `MediDex does not retain any user data once the App is uninstalled...`
            },
            {
              title: '5. Third-Party Services',
              body: `MediDex does not integrate with advertising networks...`
            },
            {
              title: '6. Children\'s Privacy',
              body: `MediDex is not intended for use by individuals under the age of 16...`
            },
            {
              title: '7. Changes to This Privacy Policy',
              body: `We may update this Privacy Policy from time to time...`
            }
          ].map(({ title, body }, i) => (
            <View key={i}>
              <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>{title}</Text>
              <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>{body}</Text>
            </View>
          ))}
        </View>

        <View style={[styles.infoCard, themeStyles.card]}>
          <Text style={[styles.subHeaderText, themeStyles.text, { fontSize: textSize + 4 }]}>
            Legal Information
          </Text>

          {[
            {
              title: 'By using the MediDex application ("the App")...',
              body: `...you agree to the following terms and conditions, governed by the laws of New Zealand:`
            },
            {
              title: '1. Source of Information',
              body: `All information provided in the App is sourced directly from Medsafe New Zealand...`
            },
            {
              title: '2. Scope of Recall Data',
              body: `Recall notices included in MediDex cover a rolling 180-day period...`
            },
            {
              title: '3. Use of Consumer Medicine Information (CMI)',
              body: `Not all medicines listed in MediDex have an official CMI sheet available...`
            },
            {
              title: '4. Medical Disclaimer',
              body: `The App is for informational purposes only. It does not replace professional medical advice...`
            },
            {
              title: '5. Privacy and Data',
              body: `MediDex does not collect, store, or transmit personal or health-related data...`
            },
            {
              title: '6. Intellectual Property',
              body: `All app content and formatting are intellectual property...`
            },
            {
              title: '7. Limitation of Liability',
              body: `MediDex and its creators are not liable for any loss, damage, or injury...`
            },
            {
              title: '8. Amendments',
              body: `We may change these Terms at any time. Continued use of the app indicates acceptance...`
            },
            {
              title: '9. Governing Law',
              body: `These Terms are governed by New Zealand law...`
            }
          ].map(({ title, body }, i) => (
            <View key={i}>
              <Text style={[styles.headerText, themeStyles.text, { fontSize: textSize }]}>{title}</Text>
              <Text style={[styles.bodyText, themeStyles.bodyText, { fontSize: textSize }]}>{body}</Text>
            </View>
          ))}
        </View>
      </ScrollView>
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: '#f0f8ff',
    flex: 1
  },
  pageTitleWrapper: {
    alignItems: 'center',
    marginTop: 60,
    marginBottom: 23
  },
  pageTitleText: {
    fontSize: 40,
    color: '#336699',
    textAlign: 'center'
  },
  headerText: {
    textAlign: 'left',
    marginTop: 10,
    marginBottom: 4,
    fontWeight: 'bold'
  },
  subHeaderText: {
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 4,
    fontWeight: 'bold',
    textDecorationLine: 'underline'
  },
  bodyText: {
    textAlign: 'left',
    marginBottom: 5
  },
  infoCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 12,
    elevation: 3,
    marginBottom: 25,
    marginHorizontal: 4
  }
})